### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by luisrudge** [lances101/Wox.Plugin.Translate#1]
![tr](https://cloud.githubusercontent.com/assets/941075/11341689/bd0f7014-91ea-11e5-96e5-a86deec9b450.gif)

```
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at TranslateWox.Main.Query(Query query) in C:\Users\Armaldio\Source\Workspaces\Workspace\TranslateWox\TranslateWox\Main.cs:line 306
   at Wox.Core.Plugin.PluginManager.ExecutePluginQuery(PluginPair pair, Query query) in c:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 193

```

**Comment by lances101** [comment]
Hello. What specific build you are using ? The one from Wox/Releases?

**Comment by luisrudge** [comment]
I'm not sure.. I just installed the Translate plugin: `wpm install Translate`

**Comment by lances101** [comment]
Ah... Okay. The version through WPM is the one that got abandoned by the initial developer and right now there is no way of removing plugins that do not work from the package manager. 

This repository is a version I maintain myself. [You can download it built here](http://discussion.getwox.com/t/translation-plugin/117/12?u=lances101)

Do a `wpm uninstall translate` before dropping the contents of the zip into the Plugins folder.

**Comment by luisrudge** [comment]
Thanks! That's very helpful! May I suggest you to add your plugin to the registry and publish this zip file in the github releases from this repo?
Thanks again!

**Comment by lances101** [comment]
I don't want there to be two plugins in the Plugin repo. So I'm waiting for some action from @qianlifeng regarding the old one. I will add the release binary here though! :smiley:

**Comment by lances101** [comment]
[Forget what I said. Here is the reupload!](https://www.getwox.com/plugin/60)

**Comment by luisrudge** [comment]
awesome! Thanks!

**Comment by luisrudge** [comment]
Sorry.. it's not working.. When I install Google Translate plugin, wox starts, crashes and quits immediately

**Comment by lances101** [comment]
The **zoo** of Wox versions that people have is killing me... I hope @happlebao solves this soon. 

If I use a fresh version of `Wox.Plugin.dll` for this plugin - it works only on the newest builds, but if I use an older one it seems to work just fine with all of them. 

Updated the plugin in WPM. Try now

**Comment by bao-qian** [comment]
@lances101 you can just use the old version. There won't be any API breaking.
What do you mean by **zoo** of Wox versions.

**Comment by luisrudge** [comment]
Now it's working. tHanks!
