### ISSUE TITLE
System.Net.WebException

### ISSUE THREAD

**Issue by seza443** [lances101/Wox.Plugin.Translate#2]
Hi, Wox crashes when running this plugin with the following stack trace

```
   à System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   à System.Net.WebClient.DownloadData(Uri address)
   à Wox.Plugin.GoogleTranslate.GoogleTranslatePlugin.TranslateText(String input, String from, String to) dans C:\Users\Boris\Documents\SourceControl\WoxStuff\Wox.Plugin.Translator\Wox.Plugin.Translate\GoogleTranslatePlugin.cs:ligne 352
   à Wox.Plugin.GoogleTranslate.GoogleTranslatePlugin.Query(Query query) dans C:\Users\Boris\Documents\SourceControl\WoxStuff\Wox.Plugin.Translator\Wox.Plugin.Translate\GoogleTranslatePlugin.cs:ligne 332
   à Wox.Core.Plugin.PluginManager.<>c__DisplayClass30_0.<QueryForPlugin>b__0() dans C:\Users\Ricky\Documents\GitHub\Wox\Wox.Core\Plugin\PluginManager.cs:ligne 192
   à Wox.Infrastructure.Stopwatch.Normal(String name, Action action) dans C:\Users\Ricky\Documents\GitHub\Wox\Wox.Infrastructure\Stopwatch.cs:ligne 29
   à Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) dans C:\Users\Ricky\Documents\GitHub\Wox\Wox.Core\Plugin\PluginManager.cs:ligne 190
```

Any idea for a fix ?

I'm using Wox 1.2.0 and I love your plugin ♥

**Comment by lances101** [comment]
Hey there. I will look into this, but I need some cooperation from you. 

In the Wox's folder, there is a Logs folder. Find the latest file and upload it's contents to [PasteBin](http://pastebin.com) or any other host of your choice.

**Comment by seza443** [comment]
Hello,

Thanks for the reply. I didn't find the Logs folder but, uninstalling and reinstalling the plugin brings magic and now **it works fine** :+1: 
It is a but confusing since I had already done that this afternoon. Anyway, the problem is gone.

So I guess this issue has no more reason to exists. 
Thanks again

**Comment by lances101** [comment]
Weird. Anyhow, if it happens again - we'll figure out what's wrong. I could not reproduce the error on any machine so far.
